package com.chordtracker

import android.content.Context
import android.os.Build
import android.util.Base64
import androidx.work.CoroutineWorker
import androidx.work.WorkerParameters
import org.json.JSONObject
import java.io.File
import java.net.HttpURLConnection
import java.net.URL

object AppSettings {
    private const val PREFS = "chord"
    const val STATS_FILE = "data.json"

    // Served to the dashboard WebView; kept in its own folder so only this
    // file (not the play logs) is reachable from it.
    fun statsDir(context: Context): File = File(context.filesDir, "stats").apply { mkdirs() }

    private fun prefs(context: Context) = context.getSharedPreferences(PREFS, Context.MODE_PRIVATE)

    val token: String get() = BuildConfig.GITHUB_TOKEN
    val repo: String get() = BuildConfig.DATA_REPO

    fun lastStatus(context: Context): String = prefs(context).getString("last_status", "never synced") ?: ""
    fun uploadedLines(context: Context): Int = prefs(context).getInt("uploaded_lines", 0)

    fun recordUpload(context: Context, totalLines: Int, status: String) {
        prefs(context).edit().putInt("uploaded_lines", totalLines).putString("last_status", status).apply()
    }

    fun recordStatus(context: Context, status: String) {
        prefs(context).edit().putString("last_status", status).apply()
    }
}

// Talks to the private data repo through GitHub's Contents API: uploads
// finished plays into inbox/ and downloads the generated dashboard data.
object Uploader {

    private fun connect(url: String, method: String, accept: String): HttpURLConnection {
        val conn = URL(url).openConnection() as HttpURLConnection
        conn.requestMethod = method
        conn.connectTimeout = 15_000
        conn.readTimeout = 30_000
        conn.setRequestProperty("Authorization", "Bearer ${AppSettings.token}")
        conn.setRequestProperty("Accept", accept)
        conn.setRequestProperty("X-GitHub-Api-Version", "2022-11-28")
        conn.setRequestProperty("User-Agent", "chord-tracker")
        return conn
    }

    // plays.jsonl is append-only, so a line offset is enough to know what's
    // already been sent.
    fun sync(context: Context): String {
        if (AppSettings.token.isBlank()) {
            return "No token in this build (set CHORD_DATA_REPO_PAT in .env)".also { AppSettings.recordStatus(context, it) }
        }

        val lines = MediaLog.readPlayLines(context)
        val already = AppSettings.uploadedLines(context)
        val pending = lines.drop(already)
        if (pending.isEmpty()) return "Nothing new to upload".also { AppSettings.recordStatus(context, it) }

        val device = Build.MODEL.replace(Regex("[^A-Za-z0-9]"), "")
        val path = "inbox/${System.currentTimeMillis()}-$device.jsonl"
        val body = JSONObject()
            .put("message", "Add ${pending.size} plays from $device")
            .put("content", Base64.encodeToString((pending.joinToString("\n") + "\n").toByteArray(), Base64.NO_WRAP))

        return try {
            val conn = connect(
                "https://api.github.com/repos/${AppSettings.repo}/contents/$path",
                "PUT", "application/vnd.github+json"
            )
            conn.doOutput = true
            conn.outputStream.use { it.write(body.toString().toByteArray()) }

            val code = conn.responseCode
            if (code == 201) {
                val msg = "Uploaded ${pending.size} plays"
                AppSettings.recordUpload(context, already + pending.size, msg)
                msg
            } else {
                val err = (conn.errorStream ?: conn.inputStream).bufferedReader().readText().take(120)
                "Upload failed ($code): $err".also { AppSettings.recordStatus(context, it) }
            }
        } catch (e: Exception) {
            "Upload error: ${e.message}".also { AppSettings.recordStatus(context, it) }
        }
    }

    // Downloads the dashboard data generated by the Actions job. Returns an
    // error message, or null on success.
    fun fetchStats(context: Context): String? {
        if (AppSettings.token.isBlank()) return "No token in this build"
        return try {
            val conn = connect(
                "https://api.github.com/repos/${AppSettings.repo}/contents/${AppSettings.STATS_FILE}",
                "GET", "application/vnd.github.raw+json"
            )
            when (val code = conn.responseCode) {
                200 -> {
                    val dir = AppSettings.statsDir(context)
                    val tmp = File(dir, "${AppSettings.STATS_FILE}.tmp")
                    conn.inputStream.use { input -> tmp.outputStream().use { input.copyTo(it) } }
                    tmp.renameTo(File(dir, AppSettings.STATS_FILE))
                    null
                }
                404 -> "No stats yet — the sync workflow hasn't produced data.json"
                else -> "Stats download failed ($code)"
            }
        } catch (e: Exception) {
            "Stats download error: ${e.message}"
        }
    }
}

class SyncWorker(context: Context, params: WorkerParameters) : CoroutineWorker(context, params) {
    override suspend fun doWork(): Result {
        val status = Uploader.sync(applicationContext)
        Uploader.fetchStats(applicationContext)
        return if (status.startsWith("Upload failed") || status.startsWith("Upload error")) Result.retry()
        else Result.success()
    }
}
